In [1]:
import sys
from pathlib import Path
prediction_mode_path = Path("../module")
sys.path.append(prediction_mode_path.as_posix())
import models_creation as pred_model

import pandas as pd

from sklearn.model_selection import train_test_split

import joblib

from sklearn.metrics import r2_score, mean_squared_error
import math

import numpy as np

In [ ]:
smiles_df = pd.read_excel('../Data/QSPR_epoxidation_model_I.xlsx')

In [3]:
smiles_df.head()

,Reaction number,SMILES,Reaction ID,Reaction: Links to Reaxys,Reactant,Product,Reaction,Number of Reaction Steps,Time (Reaction Details) [h],Temperature (Reaction Details) [C],...,Reagent,SMILES ligand,SMILES mieszanina reakcyjna,% mol liganda,% mol magnezu,stężenie katalizatora [mol/dm3],stężenie substratu M,Solvent (Reaction Details),References,Links to Reaxys
0,1,CC1=CC=C(C=CC(=O)C2=CC=CC=C2)C=C1,28455091,https://www.reaxys.com/reaxys/secured/hopinto....,4-methyl-chalcone,"(2R,3S)-epoxy-3-(4-methylphenyl)-1-phenylpropa...",CC1=CC=C(C=CC(=O)C2=CC=CC=C2)C=C1>>CC1=CC=C(C=...,1,72,0,...,"tert.-butylhydroperoxide; (R,R)-(-)-2,6-bis[2-...",OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](CCC3)N3CC4=...,CC(C)(OO)C.OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](...,12,20,0.024,0.2,tetrahydrofuran; toluene,"Article; Jaszczewska-Adamczak, Joanna A.; Mlyn...",https://www.reaxys.com/reaxys/secured/hopinto....
1,2,ClC1=CC=CC=C1C=CC(C2=CC=CC=C2)=O,25921657,https://www.reaxys.com/reaxys/secured/hopinto....,3-(2-chlorophenyl)-1-phenylpropenone,"trans‐2,3‐epoxy‐3‐(2‐chlorophenyl)‐1‐phenylpro...",ClC1=CC=CC=C1C=CC(C2=CC=CC=C2)=O>>[H][C@]3(C(C...,1,72,0,...,"tert.-butylhydroperoxide; (R,R)-(-)-2,6-bis[2-...",OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](CCC3)N3CC4=...,CC(C)(OO)C.OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](...,12,20,0.024,0.2,tetrahydrofuran; toluene,"Article; Jaszczewska-Adamczak, Joanna A.; Mlyn...",https://www.reaxys.com/reaxys/secured/hopinto....
2,3,O=C(C1=CC=C(N(=O)=O)C=C1)C=CC2=CC=CC=C2,30038384,https://www.reaxys.com/reaxys/secured/hopinto....,1-(4-nitro-phenyl)-3-phenyl-propenone,"trans-(2S,3R)-epoxy-3-phenyl-1-(4-nitrophenyl)...",O=C(C1=CC=C(N(=O)=O)C=C1)C=CC2=CC=CC=C2>>O=C(C...,1,72,0,...,"tert.-butylhydroperoxide; (R,R)-(-)-2,6-bis[2-...",OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](CCC3)N3CC4=...,CC(C)(OO)C.OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](...,12,20,0.024,0.2,tetrahydrofuran; toluene,"Article; Jaszczewska-Adamczak, Joanna A.; Mlyn...",https://www.reaxys.com/reaxys/secured/hopinto....
3,4,ClC1=CC=C(C=CC(=O)C2=CC=CC=C2)C=C1,28455092,https://www.reaxys.com/reaxys/secured/hopinto....,3-(4-chlorophenyl)-1-phenylprop-2-en-1-one,"((2R,3S)-3-(4-chlorophenyl)oxiran-2-yl) (pheny...",ClC1=CC=C(C=CC(=O)C2=CC=CC=C2)C=C1>>ClC1=CC=C(...,1,72,0,...,"tert.-butylhydroperoxide; (R,R)-(-)-2,6-bis[2-...",OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](CCC3)N3CC4=...,CC(C)(OO)C.OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](...,12,20,0.024,0.2,tetrahydrofuran; toluene,"Article; Jaszczewska-Adamczak, Joanna A.; Mlyn...",https://www.reaxys.com/reaxys/secured/hopinto....
4,5,O=C(\C=C\C1=CC=CC=C1)C1=CC=CC=C1,3763998,https://www.reaxys.com/reaxys/secured/hopinto....,"1,3-diphenyl-propen-3-one","trans-(2R,3S)-epoxy-1,3-diphenylpropan-1-one",O=C(\C=C\C1=CC=CC=C1)C1=CC=CC=C1>>[H][C@]1(O[C...,1,72,0,...,"tert.-butylhydroperoxide; (R,R)-(-)-2,6-bis[2-...",OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](CCC3)N3CC4=...,CC(C)(OO)C.OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](...,12,20,0.024,0.2,tetrahydrofuran; toluene,"Article; Jaszczewska-Adamczak, Joanna A.; Mlyn...",https://www.reaxys.com/reaxys/secured/hopinto....

In [ ]:
molecular_descriptors_df = pred_model.prepare_data('../Data/QSPR_epoxidation_model_I.xlsx')
molecular_descriptors_df.head()

100%|██████████████████████████████████████████████████████████████████████████████████| 41/41 [00:01<00:00, 26.40it/s]

Data size (rows, columns): (41, 1613)
Data size after first reduction (rows, columns): (41, 1285)
Data size after second reduction (rows, columns): (41, 1039)

,AATS0Z,AATS0are,AATS0d,AATS0dv,AATS0i,AATS0m,AATS0p,AATS0pe,AATS0s,AATS0se,...,piPC10,piPC2,piPC3,piPC4,piPC5,piPC6,piPC7,piPC8,piPC9,ee
0,21.096774,5.806774,3.096774,6.451613,154.935746,83.174801,1.660974,5.923665,3.939068,7.356725,...,6.248768,3.828641,4.356709,4.808111,5.323010,5.255866,5.476202,5.719492,6.006353,92
1,32.285714,5.973175,3.321429,7.128748,153.200722,131.707465,1.861423,6.164168,4.175784,7.587078,...,6.277700,3.828641,4.375757,4.832306,5.304548,5.232111,5.489067,5.679959,5.993806,55
2,26.400000,6.438830,3.433333,10.000000,156.786781,104.641286,1.662128,6.517330,7.696296,7.908921,...,6.459709,3.931826,4.465908,4.912655,5.417211,5.517704,5.844269,5.762837,6.101439,48
3,32.285714,5.973175,3.321429,7.128748,153.200722,131.707465,1.861423,6.164168,4.175784,7.587078,...,6.248768,3.828641,4.356709,4.808111,5.323010,5.255866,5.476202,5.719492,6.006353,97
4,22.000000,5.860000,3.142857,6.857143,153.799230,86.861521,1.707574,5.980396,4.190476,7.395751,...,6.123862,3.761200,4.297285,4.751433,5.237107,5.093750,5.418043,5.576896,5.901266,97

In [5]:
frames = [smiles_df['SMILES'], molecular_descriptors_df]
res = pd.concat(frames, axis=1)

In [6]:
res.head()

,SMILES,AATS0Z,AATS0are,AATS0d,AATS0dv,AATS0i,AATS0m,AATS0p,AATS0pe,AATS0s,...,piPC10,piPC2,piPC3,piPC4,piPC5,piPC6,piPC7,piPC8,piPC9,ee
0,CC1=CC=C(C=CC(=O)C2=CC=CC=C2)C=C1,21.096774,5.806774,3.096774,6.451613,154.935746,83.174801,1.660974,5.923665,3.939068,...,6.248768,3.828641,4.356709,4.808111,5.323010,5.255866,5.476202,5.719492,6.006353,92
1,ClC1=CC=CC=C1C=CC(C2=CC=CC=C2)=O,32.285714,5.973175,3.321429,7.128748,153.200722,131.707465,1.861423,6.164168,4.175784,...,6.277700,3.828641,4.375757,4.832306,5.304548,5.232111,5.489067,5.679959,5.993806,55
2,O=C(C1=CC=C(N(=O)=O)C=C1)C=CC2=CC=CC=C2,26.400000,6.438830,3.433333,10.000000,156.786781,104.641286,1.662128,6.517330,7.696296,...,6.459709,3.931826,4.465908,4.912655,5.417211,5.517704,5.844269,5.762837,6.101439,48
3,ClC1=CC=C(C=CC(=O)C2=CC=CC=C2)C=C1,32.285714,5.973175,3.321429,7.128748,153.200722,131.707465,1.861423,6.164168,4.175784,...,6.248768,3.828641,4.356709,4.808111,5.323010,5.255866,5.476202,5.719492,6.006353,97
4,O=C(\C=C\C1=CC=CC=C1)C1=CC=CC=C1,22.000000,5.860000,3.142857,6.857143,153.799230,86.861521,1.707574,5.980396,4.190476,...,6.123862,3.761200,4.297285,4.751433,5.237107,5.093750,5.418043,5.576896,5.901266,97

In [7]:
## load models
model_ee = joblib.load('Random_forest/random_forest_model_4_estimators_EE.joblib') #Random state 28

# Construct a dataframe for each Random Seed and predict values, additionally calculate R score and RMSE...

## EE

In [8]:
list(model_ee.feature_names_in_)

['AMID_O', 'ATSC7Z', 'NdO', 'SdO', 'VSA_EState2']

In [9]:
res.columns# [0:-9]

Index(['SMILES', 'AATS0Z', 'AATS0are', 'AATS0d', 'AATS0dv', 'AATS0i', 'AATS0m',
       'AATS0p', 'AATS0pe', 'AATS0s',
       ...
       'piPC10', 'piPC2', 'piPC3', 'piPC4', 'piPC5', 'piPC6', 'piPC7', 'piPC8',
       'piPC9', 'ee'],
      dtype='object', length=1041)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(res[res.columns], 
                                                        res['ee'], 
                                                        test_size=0.20, random_state=15)

X_train['predicted ee'] = model_ee.predict(X_train[list(model_ee.feature_names_in_)])
X_train['observed ee'] = y_train

X_test['predicted ee'] = model_ee.predict(X_test[list(model_ee.feature_names_in_)])
X_test['observed ee'] = y_test


print('Train R score: '+str(math.sqrt(r2_score(X_train['observed ee'], X_train['predicted ee']))))
print('Test R score: '+str(math.sqrt(r2_score(X_test['observed ee'], X_test['predicted ee']))))
print('Train RMSE score: '+str(math.sqrt(mean_squared_error(X_train['observed ee'], X_train['predicted ee']))))
print('Test RMSE score: '+str(math.sqrt(mean_squared_error(X_test['observed ee'], X_test['predicted ee']))))

Train R score: 0.9389590769350445
Test R score: 0.5327167434132996
Train RMSE score: 8.052561704203203
Test RMSE score: 14.016854933337301

In [11]:
with pd.ExcelWriter("../Data/ee_random_state_15.xlsx") as writer:
    X_train.to_excel(writer, sheet_name="Train", index=True)
    X_test.to_excel(writer, sheet_name="Test", index=True)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(res[res.columns], 
                                                        res['ee'], 
                                                        test_size=0.20, random_state=28)

X_train['predicted ee'] = model_ee.predict(X_train[list(model_ee.feature_names_in_)])
X_train['observed ee'] = y_train

X_test['predicted ee'] = model_ee.predict(X_test[list(model_ee.feature_names_in_)])
X_test['observed ee'] = y_test


print('Train R score: '+str(math.sqrt(r2_score(X_train['observed ee'], X_train['predicted ee']))))
print('Test R score: '+str(math.sqrt(r2_score(X_test['observed ee'], X_test['predicted ee']))))
print('Train RMSE score: '+str(math.sqrt(mean_squared_error(X_train['observed ee'], X_train['predicted ee']))))
print('Test RMSE score: '+str(math.sqrt(mean_squared_error(X_test['observed ee'], X_test['predicted ee']))))

Train R score: 0.9036721772616352
Test R score: 0.8014205167828541
Train RMSE score: 10.104628425874946
Test RMSE score: 7.999565960447827

In [13]:
with pd.ExcelWriter("../Data/ee_random_state_28.xlsx") as writer:
    X_train.to_excel(writer, sheet_name="Train", index=True)
    X_test.to_excel(writer, sheet_name="Test", index=True)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(res[res.columns], 
                                                        res['ee'], 
                                                        test_size=0.20, random_state=42)

X_train['predicted ee'] = model_ee.predict(X_train[list(model_ee.feature_names_in_)])
X_train['observed ee'] = y_train

X_test['predicted ee'] = model_ee.predict(X_test[list(model_ee.feature_names_in_)])
X_test['observed ee'] = y_test


print('Train R score: '+str(math.sqrt(r2_score(X_train['observed ee'], X_train['predicted ee']))))
print('Test R score: '+str(math.sqrt(r2_score(X_test['observed ee'], X_test['predicted ee']))))
print('Train RMSE score: '+str(math.sqrt(mean_squared_error(X_train['observed ee'], X_train['predicted ee']))))
print('Test RMSE score: '+str(math.sqrt(mean_squared_error(X_test['observed ee'], X_test['predicted ee']))))

Train R score: 0.8598058969862045
Test R score: 0.9425211967217911
Train RMSE score: 9.454248383663293
Test RMSE score: 10.450943604393922

In [15]:
with pd.ExcelWriter("../Data/ee_random_state_42.xlsx") as writer:
    X_train.to_excel(writer, sheet_name="Train", index=True)
    X_test.to_excel(writer, sheet_name="Test", index=True)