In [1]:
import pandas as pd

# Define the path to the Excel file
file_path = '../Data/Quality_epox_cla_15_cla_.xlsx'

# Define the sheets and metrics
sheets = ["MLR", "DT", "RF", "KNN", "SVM"]
metrics = ['Training Accuracy', 'Test Accuracy', 'Training Precision', 'Test Precision']
number_of_features = 10
# Initialize a dictionary to store the best models
best_models = {}

# Iterate through each sheet to find the best model
for sheet in sheets:
    # Read the data from the current sheet
    df = pd.read_excel(file_path, sheet_name=sheet)
    df_filtered = df[df['Number of features'] < number_of_features]
    # Filter the DataFrame based on the criteria
    # The model must have higher training parameters than test parameters
    filtered_df = df_filtered[(df_filtered['Training Accuracy'] > df_filtered['Test Accuracy']) & 
                     (df_filtered['Training Precision'] > df_filtered['Test Precision']) & 
                              (df_filtered['Test Precision'] > 0.6)]
    
    if not filtered_df.empty:
        # Find the row with the maximum Test Accuracy
        best_model = filtered_df.loc[filtered_df['Test Accuracy'].idxmax()]
        best_model = filtered_df.loc[filtered_df['Correlation threshold'].idxmax()]
        best_models[sheet] = best_model

# Convert the results to a DataFrame for better visualization
best_models_df = pd.DataFrame.from_dict(best_models, orient='index')

# Print the best models for each method
print("Best Models for Each Method:")
best_models_df

Best Models for Each Method:

,Unnamed: 0,Correlation threshold,Training Accuracy,Test Accuracy,Training Precision,Test Precision,Number of features,Depth number,Number of estimators,C,Gamma,Kernel
DT,169.0,0.41,0.946429,0.818182,0.972973,0.750000,5.0,3.0,NaN,NaN,NaN,NaN
RF,171.0,0.44,0.910714,0.818182,0.971429,0.750000,3.0,NaN,2.0,NaN,NaN,NaN
SVM,204.0,0.40,0.857143,0.818182,0.875000,0.666667,8.0,NaN,NaN,10.0,1.0,linear

In [2]:
import pandas as pd

# Define the path to the Excel file
file_path = '../Data/Quality_epox_cla_28_cla_.xlsx'

# Define the sheets and metrics
sheets = ["MLR", "DT", "RF", "KNN", "SVM"]
number_of_features = 10
# Initialize a dictionary to store the best models
best_models = {}

# Iterate through each sheet to find the best model
for sheet in sheets:
    # Read the data from the current sheet
    df = pd.read_excel(file_path, sheet_name=sheet)
    
    # Filter the DataFrame based on the criteria
    # The model must have fewer features than the specified limit
    df_filtered = df[df['Number of features'] < number_of_features]
    
    # Further filter based on training parameters being greater than test parameters
    filtered_df = df_filtered[(df_filtered['Training Accuracy'] > df_filtered['Test Accuracy']) & 
                              (df_filtered['Training Precision'] > df_filtered['Test Precision']) & 
                              (df_filtered['Test Precision'] > 0.6)]
    
    if not filtered_df.empty:
        # Find the row with the minimum 'Number of features'
        best_model = filtered_df.loc[filtered_df['Number of features'].idxmin()]
        best_models[sheet] = best_model

# Convert the results to a DataFrame for better visualization
best_models_df = pd.DataFrame.from_dict(best_models, orient='index')

# Print the best models for each method
print("Best Models for Each Method:")
best_models_df

Best Models for Each Method:

,Unnamed: 0,Correlation threshold,Training Accuracy,Test Accuracy,Training Precision,Test Precision,Number of features,Depth number,Number of estimators,Number of neighbors,C,Gamma,Kernel
MLR,7.0,0.42,0.785714,0.727273,0.780488,0.750000,3.0,NaN,NaN,NaN,NaN,NaN,NaN
DT,196.0,0.42,0.875000,0.818182,0.888889,0.777778,3.0,2.0,NaN,NaN,NaN,NaN,NaN
RF,133.0,0.42,0.892857,0.818182,1.000000,0.857143,3.0,NaN,2.0,NaN,NaN,NaN,NaN
KNN,49.0,0.42,0.857143,0.818182,0.885714,0.777778,3.0,NaN,NaN,3.0,NaN,NaN,NaN
SVM,252.0,0.42,0.785714,0.636364,0.794872,0.714286,3.0,NaN,NaN,NaN,0.1,1.0,linear

In [3]:
import pandas as pd

# Define the path to the Excel file
file_path = '../Data/Quality_epox_cla_42_cla_.xlsx'

# Define the sheets and metrics
sheets = ["MLR", "DT", "RF", "KNN", "SVM"]
number_of_features = 10
# Initialize a dictionary to store the best models
best_models = {}

# Iterate through each sheet to find the best model
for sheet in sheets:
    # Read the data from the current sheet
    df = pd.read_excel(file_path, sheet_name=sheet)
    
    # Filter the DataFrame based on the criteria
    # The model must have fewer features than the specified limit
    df_filtered = df[df['Number of features'] < number_of_features]
    
    # Further filter based on training parameters being greater than test parameters
    filtered_df = df_filtered[(df_filtered['Training Accuracy'] > df_filtered['Test Accuracy']) & 
                              (df_filtered['Training Precision'] > df_filtered['Test Precision']) & 
                              (df_filtered['Test Precision'] > 0.6) & 
                              (df_filtered['Test Accuracy'] > 0.6)]
    
    if not filtered_df.empty:
        # Find the row with the minimum 'Number of features'
        best_model = filtered_df.loc[filtered_df['Number of features'].idxmin()]
        best_models[sheet] = best_model

# Convert the results to a DataFrame for better visualization
best_models_df = pd.DataFrame.from_dict(best_models, orient='index')

# Print the best models for each method
print("Best Models for Each Method:")
best_models_df

Best Models for Each Method:

,Unnamed: 0,Correlation threshold,Training Accuracy,Test Accuracy,Training Precision,Test Precision,Number of features,Depth number,Number of estimators,Number of neighbors,C,Gamma,Kernel
MLR,10.0,0.45,0.785714,0.636364,0.794872,0.714286,1.0,NaN,NaN,NaN,NaN,NaN,NaN
DT,280.0,0.45,0.785714,0.636364,0.794872,0.714286,1.0,2.0,NaN,NaN,NaN,NaN,NaN
RF,190.0,0.45,0.785714,0.636364,0.794872,0.714286,1.0,NaN,2.0,NaN,NaN,NaN,NaN
KNN,70.0,0.45,0.785714,0.636364,0.794872,0.714286,1.0,NaN,NaN,3.0,NaN,NaN,NaN
SVM,361.0,0.45,0.785714,0.636364,0.794872,0.714286,1.0,NaN,NaN,NaN,0.1,1.0,rbf