In [1]:
import sys
from pathlib import Path
prediction_mode_path = Path("../module")
sys.path.append(prediction_mode_path.as_posix())
import models_creation as pred_model

import pandas as pd

from sklearn.model_selection import train_test_split

import joblib

from sklearn.metrics import r2_score, mean_squared_error
import math

import numpy as np

In [2]:
smiles_df = pd.read_excel('../Data/QSPR_epoxidation_model_III.xlsx')

In [3]:
smiles_df.head()

,Reaction: Links to Reaxys,SMILES,SMILES_substrate_1,SMILES_substrate_2,Reaction,Temperature (Reaction Details) [C],Other Conditions,Reaction Type,Yield (numerical),Yield (optical),9,10,11,ee,Reagent,Catalyst,Solvent (Reaction Details),References
0,https://www.reaxys.com/reaxys/secured/hopinto....,SC1=CC=CC=C1.O=C(C2=CC=CC=C2)/C=C/C3=CC=CC=C3,SC1=CC=CC=C1,O=C(C2=CC=CC=C2)/C=C/C3=CC=CC=C3,SC1=CC=CC=C1.O=C(C2=CC=CC=C2)/C=C/C3=CC=CC=C3>...,-78 - 25; -65,Inert atmosphere; Schlenk technique; Inert atm...,Michael Addition; Michael Addition,95,80 percent ee,NaN,NaN,NaN,80.0,"dibutylmagnesium; (S,S)-prophenol","(S,S)-prophenol",toluene,"Article; Jaszczewska-Adamczak, Joanna A.;Bacze..."
1,https://www.reaxys.com/reaxys/secured/hopinto....,O=C1CCCC=C1.SCC2=CC=CC=C2,O=C1CCCC=C1,SCC2=CC=CC=C2,O=C1CCCC=C1.SCC2=CC=CC=C2>>O=C3CCC[C@@H](SCC4=...,-78 - 25; -78,Inert atmosphere; Schlenk technique; Inert atm...,Michael Addition; Michael Addition,92,46 percent ee,NaN,NaN,NaN,46.0,"dibutylmagnesium; (S,S)-prophenol","(S,S)-prophenol",toluene,"Article; Jaszczewska-Adamczak, Joanna A.;Bacze..."
2,https://www.reaxys.com/reaxys/secured/hopinto....,CC(C)(C)S.O=C(\C=C\C1=CC=CC=C1)C1=CC=CC=C1,CC(C)(C)S,O=C(\C=C\C1=CC=CC=C1)C1=CC=CC=C1,CC(C)(C)S.O=C(\C=C\C1=CC=CC=C1)C1=CC=CC=C1>>CC...,-78 - 25; -78,Inert atmosphere; Schlenk technique; Inert atm...,Michael Addition; Michael Addition,84,95 percent ee,NaN,NaN,NaN,95.0,"dibutylmagnesium; (S,S)-prophenol","(S,S)-prophenol",toluene,"Article; Jaszczewska-Adamczak, Joanna A.;Bacze..."
3,https://www.reaxys.com/reaxys/secured/hopinto....,O=C1CCCCC=C1.SCC2=CC=CC=C2,O=C1CCCCC=C1,SCC2=CC=CC=C2,O=C1CCCCC=C1.SCC2=CC=CC=C2>>O=C3CCCC[C@@H](SCC...,-78 - 25; -78,Inert atmosphere; Schlenk technique; Inert atm...,Michael Addition; Michael Addition,83,50 percent ee,NaN,NaN,NaN,50.0,"dibutylmagnesium; (S,S)-prophenol","(S,S)-prophenol",toluene,"Article; Jaszczewska-Adamczak, Joanna A.;Bacze..."
4,https://www.reaxys.com/reaxys/secured/hopinto....,CC1=CC(CCC1)=O.SCC2=CC=CC=C2,CC1=CC(CCC1)=O,SCC2=CC=CC=C2,CC1=CC(CCC1)=O.SCC2=CC=CC=C2>>C[C@@]3(SCC4=CC=...,-78 - 25; -78,Inert atmosphere; Schlenk technique; Inert atm...,Michael Addition; Michael Addition,84,82 percent ee,NaN,NaN,NaN,82.0,"dibutylmagnesium; (S,S)-prophenol","(S,S)-prophenol",toluene,"Article; Jaszczewska-Adamczak, Joanna A.;Bacze..."

In [4]:
molecular_descriptors_df = pred_model.prepare_data('../Data/QSPR_epoxidation_model_III.xlsx')
molecular_descriptors_df.head()

C:\Users\aleks\anaconda3\envs\cheminf_gpu\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\aleks\anaconda3\envs\cheminf_gpu\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\aleks\anaconda3\envs\cheminf_gpu\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\aleks\anaconda3\envs\cheminf_gpu\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\aleks\anaconda3\envs\cheminf_gpu\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

 35%|█████████████████████████████                                                     | 22/62 [00:01<00:02, 14.60it/s]

C:\Users\aleks\anaconda3\envs\cheminf_gpu\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\aleks\anaconda3\envs\cheminf_gpu\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\aleks\anaconda3\envs\cheminf_gpu\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\aleks\anaconda3\envs\cheminf_gpu\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\aleks\anaconda3\envs\cheminf_gpu\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\aleks\anaconda3\envs\cheminf_gpu\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\aleks\anaconda3\envs\cheminf_gpu\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\aleks\anaconda3\envs\cheminf_gpu\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\aleks\anaconda3\envs\cheminf_gpu\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\aleks\anaconda3\envs\cheminf_gpu\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

100%|██████████████████████████████████████████████████████████████████████████████████| 62/62 [00:01<00:00, 35.23it/s]

Data size (rows, columns): (62, 3874)
Data size after first reduction (rows, columns): (62, 3227)
Data size after second reduction (rows, columns): (62, 1340)

,AATS0Z,AATS0are,AATS0d,AATS0dv,AATS0i,AATS0m,AATS0p,AATS0pe,AATS0s,AATS0se,...,C_FP_1991,C_FP_1992,C_FP_1996,C_FP_1999,C_FP_2017,C_FP_2023,C_FP_2029,C_FP_2033,C_FP_2041,ee
0,26.682927,5.770088,3.024390,6.178260,153.267812,105.649934,1.844467,5.906402,3.601607,7.350701,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,80.0
1,25.935484,5.706245,2.580645,4.751892,158.057747,102.435555,1.691055,5.821371,3.519689,7.342506,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.0
2,23.860465,5.661247,2.744186,4.914154,157.443307,94.120542,1.670321,5.779477,3.312805,7.283060,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,95.0
3,24.764706,5.671282,2.529412,4.450254,158.718230,97.699954,1.650025,5.783676,3.334128,7.311622,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0
4,24.764706,5.671282,2.588235,4.567901,158.718230,97.699954,1.650025,5.783676,3.349651,7.311622,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,82.0

In [5]:
frames = [smiles_df['SMILES'], molecular_descriptors_df]
res = pd.concat(frames, axis=1)

In [6]:
res.head()

,SMILES,AATS0Z,AATS0are,AATS0d,AATS0dv,AATS0i,AATS0m,AATS0p,AATS0pe,AATS0s,...,C_FP_1991,C_FP_1992,C_FP_1996,C_FP_1999,C_FP_2017,C_FP_2023,C_FP_2029,C_FP_2033,C_FP_2041,ee
0,SC1=CC=CC=C1.O=C(C2=CC=CC=C2)/C=C/C3=CC=CC=C3,26.682927,5.770088,3.024390,6.178260,153.267812,105.649934,1.844467,5.906402,3.601607,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,80.0
1,O=C1CCCC=C1.SCC2=CC=CC=C2,25.935484,5.706245,2.580645,4.751892,158.057747,102.435555,1.691055,5.821371,3.519689,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46.0
2,CC(C)(C)S.O=C(\C=C\C1=CC=CC=C1)C1=CC=CC=C1,23.860465,5.661247,2.744186,4.914154,157.443307,94.120542,1.670321,5.779477,3.312805,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,95.0
3,O=C1CCCCC=C1.SCC2=CC=CC=C2,24.764706,5.671282,2.529412,4.450254,158.718230,97.699954,1.650025,5.783676,3.334128,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,50.0
4,CC1=CC(CCC1)=O.SCC2=CC=CC=C2,24.764706,5.671282,2.588235,4.567901,158.718230,97.699954,1.650025,5.783676,3.349651,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,82.0

In [7]:
## load models
model_ee = joblib.load('models/random_forest_model_8_estimators_EE.joblib') #Random state 15

# Construct a dataframe for each Random Seed and predict values, additionally calculate R score and RMSE...

## EE

In [8]:
list(model_ee.feature_names_in_)

['ATSC5v', 'NdssC']

In [9]:
res.columns[0:-9]

Index(['SMILES', 'AATS0Z', 'AATS0are', 'AATS0d', 'AATS0dv', 'AATS0i', 'AATS0m',
       'AATS0p', 'AATS0pe', 'AATS0s',
       ...
       'C_FP_1947', 'C_FP_1953', 'C_FP_1957', 'C_FP_1963', 'C_FP_1966',
       'C_FP_1970', 'C_FP_1976', 'C_FP_1979', 'C_FP_1985', 'C_FP_1991'],
      dtype='object', length=1333)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(res[res.columns], 
                                                        res['ee'], 
                                                        test_size=0.15, random_state=15)

X_train['predicted ee'] = model_ee.predict(X_train[list(model_ee.feature_names_in_)])
X_train['observed ee'] = y_train

X_test['predicted ee'] = model_ee.predict(X_test[list(model_ee.feature_names_in_)])
X_test['observed ee'] = y_test


print('Train R score: '+str(math.sqrt(r2_score(X_train['observed ee'], X_train['predicted ee']))))
print('Test R score: '+str(math.sqrt(r2_score(X_test['observed ee'], X_test['predicted ee']))))
print('Train RMSE score: '+str(math.sqrt(mean_squared_error(X_train['observed ee'], X_train['predicted ee']))))
print('Test RMSE score: '+str(math.sqrt(mean_squared_error(X_test['observed ee'], X_test['predicted ee']))))

Train R score: 0.8828553308907829
Test R score: 0.6256473638939778
Train RMSE score: 15.80924960416765
Test RMSE score: 29.84004885426631

In [11]:
with pd.ExcelWriter("../Data/ee_random_state_15.xlsx") as writer:
    X_train.to_excel(writer, sheet_name="Train", index=True)
    X_test.to_excel(writer, sheet_name="Test", index=True)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(res[res.columns], 
                                                        res['ee'], 
                                                        test_size=0.15, random_state=28)

X_train['predicted ee'] = model_ee.predict(X_train[list(model_ee.feature_names_in_)])
X_train['observed ee'] = y_train

X_test['predicted ee'] = model_ee.predict(X_test[list(model_ee.feature_names_in_)])
X_test['observed ee'] = y_test


print('Train R score: '+str(math.sqrt(r2_score(X_train['observed ee'], X_train['predicted ee']))))
print('Test R score: '+str(math.sqrt(r2_score(X_test['observed ee'], X_test['predicted ee']))))
print('Train RMSE score: '+str(math.sqrt(mean_squared_error(X_train['observed ee'], X_train['predicted ee']))))
print('Test RMSE score: '+str(math.sqrt(mean_squared_error(X_test['observed ee'], X_test['predicted ee']))))

Train R score: 0.8423119303437304
Test R score: 0.8386546147705874
Train RMSE score: 18.798021937321217
Test RMSE score: 18.776996190485313

In [13]:
with pd.ExcelWriter("../Data/ee_random_state_28.xlsx") as writer:
    X_train.to_excel(writer, sheet_name="Train", index=True)
    X_test.to_excel(writer, sheet_name="Test", index=True)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(res[res.columns], 
                                                        res['ee'], 
                                                        test_size=0.15, random_state=42)

X_train['predicted ee'] = model_ee.predict(X_train[list(model_ee.feature_names_in_)])
X_train['observed ee'] = y_train

X_test['predicted ee'] = model_ee.predict(X_test[list(model_ee.feature_names_in_)])
X_test['observed ee'] = y_test


print('Train R score: '+str(math.sqrt(r2_score(X_train['observed ee'], X_train['predicted ee']))))
print('Test R score: '+str(math.sqrt(r2_score(X_test['observed ee'], X_test['predicted ee']))))
print('Train RMSE score: '+str(math.sqrt(mean_squared_error(X_train['observed ee'], X_train['predicted ee']))))
print('Test RMSE score: '+str(math.sqrt(mean_squared_error(X_test['observed ee'], X_test['predicted ee']))))

Train R score: 0.8652031661734313
Test R score: 0.7165558738269712
Train RMSE score: 16.943071283365985
Test RMSE score: 26.406911973951065

In [15]:
with pd.ExcelWriter("../Data/ee_random_state_42.xlsx") as writer:
    X_train.to_excel(writer, sheet_name="Train", index=True)
    X_test.to_excel(writer, sheet_name="Test", index=True)