In [1]:
import sys
from pathlib import Path
prediction_mode_path = Path("../module")
sys.path.append(prediction_mode_path.as_posix())
import models_creation as pred_model

import pandas as pd

from sklearn.model_selection import train_test_split

import joblib

from sklearn.metrics import r2_score, mean_squared_error
import math

import numpy as np

In [2]:
smiles_df = pd.read_excel('../Data/QSPR_epoxidation_model_II.xlsx')

In [3]:
smiles_df.head()

,Reaction number,SMILES,Reaction ID,Reaction: Links to Reaxys,Reactant,Product,Reaction,Number of Reaction Steps,Time (Reaction Details) [h],Temperature (Reaction Details) [C],...,Reagent,SMILES ligand,SMILES mieszanina reakcyjna,% mol liganda,% mol magnezu,stężenie katalizatora [mol/dm3],stężenie substratu M,Solvent (Reaction Details),References,Links to Reaxys
0,1,CC1=CC=C(C=CC(=O)C2=CC=CC=C2)C=C1,28455091.0,https://www.reaxys.com/reaxys/secured/hopinto....,4-methyl-chalcone,"(2R,3S)-epoxy-3-(4-methylphenyl)-1-phenylpropa...",CC1=CC=C(C=CC(=O)C2=CC=CC=C2)C=C1>>CC1=CC=C(C=...,1.0,72.0,0.0,...,"tert.-butylhydroperoxide; (R,R)-(-)-2,6-bis[2-...",OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](CCC3)N3CC4=...,CC(C)(OO)C.OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](...,12.0,20.0,0.024,0.2,tetrahydrofuran; toluene,"Article; Jaszczewska-Adamczak, Joanna A.; Mlyn...",https://www.reaxys.com/reaxys/secured/hopinto....
1,2,ClC1=CC=CC=C1C=CC(C2=CC=CC=C2)=O,25921657.0,https://www.reaxys.com/reaxys/secured/hopinto....,3-(2-chlorophenyl)-1-phenylpropenone,"trans‐2,3‐epoxy‐3‐(2‐chlorophenyl)‐1‐phenylpro...",ClC1=CC=CC=C1C=CC(C2=CC=CC=C2)=O>>[H][C@]3(C(C...,1.0,72.0,0.0,...,"tert.-butylhydroperoxide; (R,R)-(-)-2,6-bis[2-...",OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](CCC3)N3CC4=...,CC(C)(OO)C.OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](...,12.0,20.0,0.024,0.2,tetrahydrofuran; toluene,"Article; Jaszczewska-Adamczak, Joanna A.; Mlyn...",https://www.reaxys.com/reaxys/secured/hopinto....
2,3,ClC1=CC=C(C=CC(=O)C2=CC=CC=C2)C=C1,28455092.0,https://www.reaxys.com/reaxys/secured/hopinto....,3-(4-chlorophenyl)-1-phenylprop-2-en-1-one,"((2R,3S)-3-(4-chlorophenyl)oxiran-2-yl) (pheny...",ClC1=CC=C(C=CC(=O)C2=CC=CC=C2)C=C1>>ClC1=CC=C(...,1.0,72.0,0.0,...,"tert.-butylhydroperoxide; (R,R)-(-)-2,6-bis[2-...",OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](CCC3)N3CC4=...,CC(C)(OO)C.OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](...,12.0,20.0,0.024,0.2,tetrahydrofuran; toluene,"Article; Jaszczewska-Adamczak, Joanna A.; Mlyn...",https://www.reaxys.com/reaxys/secured/hopinto....
3,4,O=C(\C=C\C1=CC=CC=C1)C1=CC=CC=C1,3763998.0,https://www.reaxys.com/reaxys/secured/hopinto....,"1,3-diphenyl-propen-3-one","trans-(2R,3S)-epoxy-1,3-diphenylpropan-1-one",O=C(\C=C\C1=CC=CC=C1)C1=CC=CC=C1>>[H][C@]1(O[C...,1.0,72.0,0.0,...,"tert.-butylhydroperoxide; (R,R)-(-)-2,6-bis[2-...",OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](CCC3)N3CC4=...,CC(C)(OO)C.OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](...,12.0,20.0,0.024,0.2,tetrahydrofuran; toluene,"Article; Jaszczewska-Adamczak, Joanna A.; Mlyn...",https://www.reaxys.com/reaxys/secured/hopinto....
4,5,O=C1C(CCC2=C1C=CC=C2)=CC3=CC=CC=C3,33324923.0,https://www.reaxys.com/reaxys/secured/hopinto....,2-benzylidene-1-tetralone,"3′‐phenyl‐3,4‐dihydro‐1H-spiro(naphthalene‐2,2...",O=C1C(CCC2=C1C=CC=C2)=CC3=CC=CC=C3>>O=C4C5=CC=...,1.0,72.0,0.0,...,"tert.-butylhydroperoxide; (R,R)-(-)-2,6-bis[2-...",OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](CCC3)N3CC4=...,CC(C)(OO)C.OC(C1=CC=CC=C1)(C2=CC=CC=C2)[C@@H](...,12.0,20.0,0.024,0.2,tetrahydrofuran; toluene,"Article; Jaszczewska-Adamczak, Joanna A.; Mlyn...",https://www.reaxys.com/reaxys/secured/hopinto....

In [4]:
molecular_descriptors_df = pred_model.prepare_data('../Data/QSPR_epoxidation_model_II.xlsx')
molecular_descriptors_df.head()

100%|██████████████████████████████████████████████████████████████████████████████████| 67/67 [00:01<00:00, 38.64it/s]

Data size (rows, columns): (67, 3874)
Data size after first reduction (rows, columns): (67, 3329)
Data size after second reduction (rows, columns): (67, 3329)

C:\Users\aleks\Desktop\epoxidation_models\to_github\Model_II\QSPR\../module\models_creation.py:72: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  molecular_descriptors_cleaned[targets] = df[targets]

,AATS0Z,AATS0are,AATS0d,AATS0dv,AATS0i,AATS0m,AATS0p,AATS0pe,AATS0s,AATS0se,...,C_FP_2039,C_FP_2040,C_FP_2041,C_FP_2042,C_FP_2043,C_FP_2044,C_FP_2045,C_FP_2046,C_FP_2047,ee
0,21.096774,5.806774,3.096774,6.451613,154.935746,83.174801,1.660974,5.923665,3.939068,7.356725,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,92
1,32.285714,5.973175,3.321429,7.128748,153.200722,131.707465,1.861423,6.164168,4.175784,7.587078,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,55
2,32.285714,5.973175,3.321429,7.128748,153.200722,131.707465,1.861423,6.164168,4.175784,7.587078,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,97
3,22.000000,5.860000,3.142857,6.857143,153.799230,86.861521,1.707574,5.980396,4.190476,7.395751,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,97
4,21.562500,5.820625,3.375000,6.687500,154.056327,85.083842,1.696221,5.941753,3.793403,7.362468,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74

In [5]:
frames = [smiles_df['SMILES'], molecular_descriptors_df]
res = pd.concat(frames, axis=1)

In [6]:
res.head()

,SMILES,AATS0Z,AATS0are,AATS0d,AATS0dv,AATS0i,AATS0m,AATS0p,AATS0pe,AATS0s,...,C_FP_2039,C_FP_2040,C_FP_2041,C_FP_2042,C_FP_2043,C_FP_2044,C_FP_2045,C_FP_2046,C_FP_2047,ee
0,CC1=CC=C(C=CC(=O)C2=CC=CC=C2)C=C1,21.096774,5.806774,3.096774,6.451613,154.935746,83.174801,1.660974,5.923665,3.939068,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,92
1,ClC1=CC=CC=C1C=CC(C2=CC=CC=C2)=O,32.285714,5.973175,3.321429,7.128748,153.200722,131.707465,1.861423,6.164168,4.175784,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,55
2,ClC1=CC=C(C=CC(=O)C2=CC=CC=C2)C=C1,32.285714,5.973175,3.321429,7.128748,153.200722,131.707465,1.861423,6.164168,4.175784,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,97
3,O=C(\C=C\C1=CC=CC=C1)C1=CC=CC=C1,22.000000,5.860000,3.142857,6.857143,153.799230,86.861521,1.707574,5.980396,4.190476,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,97
4,O=C1C(CCC2=C1C=CC=C2)=CC3=CC=CC=C3,21.562500,5.820625,3.375000,6.687500,154.056327,85.083842,1.696221,5.941753,3.793403,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74

In [7]:
## load models
model_ee = joblib.load('models/RF_model_1__EE_reg.joblib') #Random state 28

# Construct a dataframe for each Random Seed and predict values, additionally calculate R score and RMSE...

## EE

In [8]:
list(model_ee.feature_names_in_)

['C2SP2', 'C_FP_1308']

In [9]:
res.columns[0:-9]

Index(['SMILES', 'AATS0Z', 'AATS0are', 'AATS0d', 'AATS0dv', 'AATS0i', 'AATS0m',
       'AATS0p', 'AATS0pe', 'AATS0s',
       ...
       'C_FP_2030', 'C_FP_2031', 'C_FP_2032', 'C_FP_2033', 'C_FP_2034',
       'C_FP_2035', 'C_FP_2036', 'C_FP_2037', 'C_FP_2038', 'C_FP_2039'],
      dtype='object', length=3322)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(res[res.columns], 
                                                        res['ee'], 
                                                        test_size=0.15, random_state=15)

X_train['predicted ee'] = model_ee.predict(X_train[list(model_ee.feature_names_in_)])
X_train['observed ee'] = y_train

X_test['predicted ee'] = model_ee.predict(X_test[list(model_ee.feature_names_in_)])
X_test['observed ee'] = y_test


print('Train R score: '+str(math.sqrt(r2_score(X_train['observed ee'], X_train['predicted ee']))))
print('Test R score: '+str(math.sqrt(r2_score(X_test['observed ee'], X_test['predicted ee']))))
print('Train RMSE score: '+str(math.sqrt(mean_squared_error(X_train['observed ee'], X_train['predicted ee']))))
print('Test RMSE score: '+str(math.sqrt(mean_squared_error(X_test['observed ee'], X_test['predicted ee']))))

Train R score: 0.8001455567060167
Test R score: 0.6154392410228418
Train RMSE score: 25.17733379527184
Test RMSE score: 32.98986263643377

In [11]:
with pd.ExcelWriter("../Data/ee_random_state_15.xlsx") as writer:
    X_train.to_excel(writer, sheet_name="Train", index=True)
    X_test.to_excel(writer, sheet_name="Test", index=True)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(res[res.columns], 
                                                        res['ee'], 
                                                        test_size=0.15, random_state=28)

X_train['predicted ee'] = model_ee.predict(X_train[list(model_ee.feature_names_in_)])
X_train['observed ee'] = y_train

X_test['predicted ee'] = model_ee.predict(X_test[list(model_ee.feature_names_in_)])
X_test['observed ee'] = y_test


print('Train R score: '+str(math.sqrt(r2_score(X_train['observed ee'], X_train['predicted ee']))))
print('Test R score: '+str(math.sqrt(r2_score(X_test['observed ee'], X_test['predicted ee']))))
print('Train RMSE score: '+str(math.sqrt(mean_squared_error(X_train['observed ee'], X_train['predicted ee']))))
print('Test RMSE score: '+str(math.sqrt(mean_squared_error(X_test['observed ee'], X_test['predicted ee']))))

Train R score: 0.7733180251076206
Test R score: 0.8392044680432169
Train RMSE score: 27.545857313365847
Test RMSE score: 21.274352444906633

In [13]:
with pd.ExcelWriter("../Data/ee_random_state_28.xlsx") as writer:
    X_train.to_excel(writer, sheet_name="Train", index=True)
    X_test.to_excel(writer, sheet_name="Test", index=True)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(res[res.columns], 
                                                        res['ee'], 
                                                        test_size=0.15, random_state=42)

X_train['predicted ee'] = model_ee.predict(X_train[list(model_ee.feature_names_in_)])
X_train['observed ee'] = y_train

X_test['predicted ee'] = model_ee.predict(X_test[list(model_ee.feature_names_in_)])
X_test['observed ee'] = y_test


print('Train R score: '+str(math.sqrt(r2_score(X_train['observed ee'], X_train['predicted ee']))))
print('Test R score: '+str(math.sqrt(r2_score(X_test['observed ee'], X_test['predicted ee']))))
print('Train RMSE score: '+str(math.sqrt(mean_squared_error(X_train['observed ee'], X_train['predicted ee']))))
print('Test RMSE score: '+str(math.sqrt(mean_squared_error(X_test['observed ee'], X_test['predicted ee']))))

Train R score: 0.7895117506735441
Test R score: 0.7486001445390318
Train RMSE score: 26.467862912707663
Test RMSE score: 27.368299706955156

In [15]:
with pd.ExcelWriter("../Data/ee_random_state_42.xlsx") as writer:
    X_train.to_excel(writer, sheet_name="Train", index=True)
    X_test.to_excel(writer, sheet_name="Test", index=True)